spring:
  server:
      port: 8081
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    profiles : test
  redis:
    host: r-wz9c6872083f2214.redis.rds.aliyuncs.com
    port: 6379
    password: Redis2017
    database: 0
  datasource:
    name: test
    url: jdbc:mysql://rdspower.mysql.rds.aliyuncs.com:3306/power?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: power_root
    password: power#root@2017
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
mybatis:
  mapperLocations: classpath*:/mybatis/**/**/*.xml
  typeAliasesPackage: com.power.domain,com.power.dto
